# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
RegionalOffice.create(name: 'East Africa')
NationalOffice.create(name: 'Ethiopia', regional_office_id: 1)
NationalOffice.create(name: 'Kenya', regional_office_id: 1)
NationalOffice.create(name: 'Rwanda', regional_office_id: 1)
NationalOffice.create(name: 'Somalia', regional_office_id: 1)
NationalOffice.create(name: 'South Sudan', regional_office_id: 1)
NationalOffice.create(name: 'Sudan', regional_office_id: 1)
NationalOffice.create(name: 'Tanzania', regional_office_id: 1)
NationalOffice.create(name: 'Uganda', regional_office_id: 1)
NationalOffice.create(name: 'Burundi', regional_office_id: 1)

RegionalOffice.create(name: 'East Asia')
NationalOffice.create(name: 'Cambodia', regional_office_id: 2)
NationalOffice.create(name: 'China', regional_office_id: 2)
NationalOffice.create(name: 'DPR Korea', regional_office_id: 2)
NationalOffice.create(name: 'Laos', regional_office_id: 2)
NationalOffice.create(name: 'Mongolia', regional_office_id: 2)
NationalOffice.create(name: 'Myanmar', regional_office_id: 2)
NationalOffice.create(name: 'Thailand', regional_office_id: 2)
NationalOffice.create(name: 'Vietnam', regional_office_id: 2)

RegionalOffice.create(name: 'LAC')
NationalOffice.create(name: 'Bolivia', regional_office_id: 3)
NationalOffice.create(name: 'Brazil', regional_office_id: 3)
NationalOffice.create(name: 'Chile', regional_office_id: 3)
NationalOffice.create(name: 'Colombia', regional_office_id: 3)
NationalOffice.create(name: 'Costa Rica', regional_office_id: 3)
NationalOffice.create(name: 'Dominican Republic', regional_office_id: 3)
NationalOffice.create(name: 'Ecuador', regional_office_id: 3)
NationalOffice.create(name: 'El Salvador', regional_office_id: 3)
NationalOffice.create(name: 'Guatemala', regional_office_id: 3)
NationalOffice.create(name: 'Haiti', regional_office_id: 3)
NationalOffice.create(name: 'Honduras', regional_office_id: 3)
NationalOffice.create(name: 'Mexico', regional_office_id: 3)
NationalOffice.create(name: 'Nicaragua', regional_office_id: 3)
NationalOffice.create(name: 'Peru', regional_office_id: 3)


RegionalOffice.create(name: 'MEER')
NationalOffice.create(name: 'Afghanistan', regional_office_id: 4)
NationalOffice.create(name: 'Albania & Kosovo', regional_office_id: 4)
NationalOffice.create(name: 'Armenia', regional_office_id: 4)
NationalOffice.create(name: 'Azerbaijan', regional_office_id: 4)
NationalOffice.create(name: 'Bosnia-Herzegovina', regional_office_id: 4)
NationalOffice.create(name: 'Georgia', regional_office_id: 4)
NationalOffice.create(name: 'Jerusalem, West Bank & Gaza', regional_office_id: 4)
NationalOffice.create(name: 'Lebanon', regional_office_id: 4)
NationalOffice.create(name: 'Pakistan', regional_office_id: 4)
NationalOffice.create(name: 'Romania', regional_office_id: 4)

RegionalOffice.create(name: 'South Asia & Pacific')
NationalOffice.create(name: 'Bangladesh', regional_office_id: 5)
NationalOffice.create(name: 'India', regional_office_id: 5)
NationalOffice.create(name: 'Indonesia', regional_office_id: 5)
NationalOffice.create(name: 'Nepal', regional_office_id: 5)
NationalOffice.create(name: 'Pacific Timor Leste', regional_office_id: 5)
NationalOffice.create(name: 'Philippines', regional_office_id: 5)
NationalOffice.create(name: 'Sri Lanka', regional_office_id: 5)

RegionalOffice.create(name: 'Southern Africa')
NationalOffice.create(name: 'Angola', regional_office_id: 6)
NationalOffice.create(name: 'DRC', regional_office_id: 6)
NationalOffice.create(name: 'Lesotho', regional_office_id: 6)
NationalOffice.create(name: 'Malawi', regional_office_id: 6)
NationalOffice.create(name: 'Mozambique', regional_office_id: 6)
NationalOffice.create(name: 'South Africa', regional_office_id: 6)
NationalOffice.create(name: 'Swaziland', regional_office_id: 6)
NationalOffice.create(name: 'Zambia', regional_office_id: 6)
NationalOffice.create(name: 'Zimbabwe', regional_office_id: 6)

RegionalOffice.create(name: 'West Africa')
NationalOffice.create(name: 'Chad', regional_office_id: 7)
NationalOffice.create(name: 'Ghana', regional_office_id: 7)
NationalOffice.create(name: 'Mali', regional_office_id: 7)
NationalOffice.create(name: 'Mauritania', regional_office_id: 7)
NationalOffice.create(name: 'Niger', regional_office_id: 7)
NationalOffice.create(name: 'Senegal', regional_office_id: 7)
NationalOffice.create(name: 'Sierra Leone', regional_office_id: 7)

Group.create(name: 'Men')
Group.create(name: 'Boys')
Group.create(name: 'Women')
Group.create(name: 'Girls')
Group.create(name: 'Leadership')